string pump_id
string order_number
string drug_name # The long name of a drug
string drug_short # The short name of a dug
string drug_id # Optional. Identifier of drug information.
string catalog_name # Optional
string therapy_mode
string total_dose
string total_dose_unit
string total_time # In minutes
string time_unit
string infusion_rate
string rate_unit
string vtbi_value
string vtbi_unit
string amount_value
string amount_unit
string volume_value # In ml
string volume_unit
string height_value
string height_unit 
string weight_value
string weight_unit
string patient_id
